## Accessing an Array

## Indexing and Slicing NumPy Arrays

NumPy arrays can be indexed and sliced in several ways depending on the number of dimensions.

### Indexing:

Indexing follows a simple rule that we may have encountered before. Let's give it a try.

- 1D Array: array_name[idx] (Similar to Python list)
- 2D Array: array_name[row_idx, col_idx] (Similar to Matrix)
- ND Array: array_name[dim1_idx, dim2_idx, ..., dimN_idx]

**OR**

- 2D Array: array_name[row_idx][col_idx]
- ND Array: array_name[dim1_idx][dim2_idx] ... [dimN_idx]

### Slicing:

Slicing follows the same rule as indexing. The only difference is that for each dimension we provide it with a range of indeces and sometimes (optional) step size (similar to arange() function discussed above).

- 1D Array: array_name[idx1:idx2:step]
- 2D Array: array_name[row_idx1:row_idx2:step1, col_idx1:col_idx2:step2]
- ND Array: array_name[dim1_idx1:dim1_idx2:step1, ..., dimN_idx1:dimN_idx2:stepN]

In [1]:
import numpy as np

In [2]:
# 1D Array
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [3]:
print(a[3])

4


In [4]:
a[2::1]

array([3, 4, 5])

In [5]:
a[::-1]

array([5, 4, 3, 2, 1])

In [11]:
a[1:5:2]

array([2, 4])

In [ ]:
# 2D Array
arr = np.array([
    [0, 5, 3, 4],
    [2, 0, 0, 5],
    [6, 6, 2, 0],
    [6, 2, 6, 6],
    [6, 2, 4, 7]
    ])
arr

array([[0, 5, 3, 4],
       [2, 0, 0, 5],
       [6, 6, 2, 0],
       [6, 2, 6, 6],
       [6, 2, 4, 7]])

In [ ]:
#2D Array: array_name[row_idx, col_idx] (Similar to Matrix)
arr[2, -1] #arr [2][-1]

np.int64(0)

In [ ]:
# Slicing 2D Array
# array_name[row_idx1:row_idx2:step1, col_idx1:col_idx2:step2]
arr[3, 1:3]

array([2, 6])

In [ ]:
arr[1:4, 2:]

array([[0, 5],
       [2, 0],
       [6, 6]])

In [44]:
arr[:, -1:]

array([[4],
       [5],
       [0],
       [6],
       [7]])

In [45]:
arr[2:4, 1:3]

array([[6, 2],
       [2, 6]])

In [47]:
arr[2:4]

array([[6, 6, 2, 0],
       [6, 2, 6, 6]])

In [49]:
array = np.array(
    [
        [
            [1, 3, 9],
            [8, 9, 8],
            [2, 4, 5],
            [4, 1, 7]
        ],

       [
           [3, 7, 1],
           [1, 0, 6],
           [4, 7, 2],
           [0, 8, 8]
        ],

       [
           [4, 9, 7],
           [5, 4, 9],
           [1, 9, 0],
           [5, 9, 3]
        ]
    ]
)

In [ ]:
# indexing
# ND Array: array_name[dim1_idx, dim2_idx, ..., dimN_idx]
print(array[1, -1, 1])

8


In [52]:
# Slicing
# ND Array: array_name[dim1_idx1:dim1_idx2:step1, ..., dimN_idx1:dimN_idx2:stepN]
print(array[:, 1, -2:])

[[9 8]
 [0 6]
 [4 9]]


In [55]:
print(array[:, 1:3, 1:2])

[[[9]
  [4]]

 [[0]
  [7]]

 [[4]
  [9]]]


In [56]:
# to give the slicing data to developer 
big_data = np.random.randint(0,255, size = (10, 16, 3, 32,32), dtype=int)

In [57]:
data1 = big_data[0, :3]

In [58]:
data1.shape

(3, 3, 32, 32)