## NumPy Array Properties and Methods

NumPy arrays have several useful properties and methods that can be used to manipulate them.

- `shape`: Property that returns the dimensions of the array
- `ndim`: Property that returns number of array dimensions
- `dtype`: Property that returns data-type of the array’s elements
- `T`: Transpose of the array’s elements

---

- `reshape()`: Method to change the dimensions of an array. The product of old dimensions should match the product of new dimensions
- `ravel()`: Method that collapses all values into a single axis or dimension and returns view of original array
- `flatten()`: Method that collapses all values into a single axis or dimension and returns an independent copy of original array
- `sum()`: Method that returns the sum of all elements in an array
- `cumsum()`: Method that returns cumulative sum over given axis
- `prod()`: Method that compute product over given axis
- `max()`: Method that returns the maximum along a given axis
- `argmax()`: Method that returns indeces of the maximum values along a given axis
- `clip()`: Clip values beyond range to threshold values
- `np.concatenate()`: Method to concatenate two or more arrays
- `np.split()`: Method to split an array into multiple sub-arrays
- `np.vstack()`: Method to stack arrays vertically
- `np.hstack()`: Method to stack arrays horizontally

In [1]:

import numpy as np

a = np.random.randint(10,50, size = (5, 2, 3), dtype="int16")

In [2]:
a.shape

(5, 2, 3)

In [3]:
a.ndim

3

In [4]:
a.dtype

dtype('int16')

In [5]:
a.T

array([[[45, 41, 48, 18, 29],
        [35, 26, 40, 22, 39]],

       [[33, 49, 42, 15, 17],
        [25, 14, 35, 39, 34]],

       [[46, 28, 28, 22, 13],
        [49, 15, 22, 47, 32]]], dtype=int16)

In [6]:
a.size

30

In [7]:
a = np.random.randint(10,50, size = (5, 4), dtype="int16")
a

array([[19, 28, 37, 31],
       [16, 22, 41, 19],
       [22, 21, 43, 27],
       [14, 38, 39, 21],
       [39, 43, 28, 43]], dtype=int16)

In [8]:
b = a.reshape(2,5,2)
b

array([[[19, 28],
        [37, 31],
        [16, 22],
        [41, 19],
        [22, 21]],

       [[43, 27],
        [14, 38],
        [39, 21],
        [39, 43],
        [28, 43]]], dtype=int16)

In [9]:
a.reshape(4,-1)

array([[19, 28, 37, 31, 16],
       [22, 41, 19, 22, 21],
       [43, 27, 14, 38, 39],
       [21, 39, 43, 28, 43]], dtype=int16)

In [10]:
a.flatten() #a.ravel()

array([19, 28, 37, 31, 16, 22, 41, 19, 22, 21, 43, 27, 14, 38, 39, 21, 39,
       43, 28, 43], dtype=int16)

In [11]:
a

array([[19, 28, 37, 31],
       [16, 22, 41, 19],
       [22, 21, 43, 27],
       [14, 38, 39, 21],
       [39, 43, 28, 43]], dtype=int16)

In [12]:
a.sum()

np.int64(591)

In [13]:
a.sum(axis = 0)

array([110, 152, 188, 141])

In [14]:
a.sum(axis = 1)

array([115,  98, 113, 112, 153])

## 0 -> column wise -> vertical
## 1 -> row wise -> horizontal

In [15]:
a.trace() # diagonal sum

np.int64(105)

In [16]:

a.cumsum(axis = 1)

array([[ 19,  47,  84, 115],
       [ 16,  38,  79,  98],
       [ 22,  43,  86, 113],
       [ 14,  52,  91, 112],
       [ 39,  82, 110, 153]])

In [17]:
a.prod(dtype=float)

np.float64(7.895587489322794e+28)

In [18]:
a.prod(axis = 0)

array([ 3651648, 21137424, 71232252, 14360409])

In [19]:
a.cumprod(axis = 1)

array([[     19,     532,   19684,  610204],
       [     16,     352,   14432,  274208],
       [     22,     462,   19866,  536382],
       [     14,     532,   20748,  435708],
       [     39,    1677,   46956, 2019108]])

In [20]:
a

array([[19, 28, 37, 31],
       [16, 22, 41, 19],
       [22, 21, 43, 27],
       [14, 38, 39, 21],
       [39, 43, 28, 43]], dtype=int16)

In [21]:
a.argmax(axis = 0)

array([4, 4, 2, 4])

In [22]:
a.argmin(axis = 1)

array([0, 0, 1, 0, 2])

In [23]:
a.clip(min= 20, max = 40)

array([[20, 28, 37, 31],
       [20, 22, 40, 20],
       [22, 21, 40, 27],
       [20, 38, 39, 21],
       [39, 40, 28, 40]], dtype=int16)

In [ ]:
# Concat or Joining

In [24]:
arr1 = np.random.randint(1,100, size = (3,3))
arr2 = np.random.randint(1,100, size = (3,3))

In [25]:
arr1, arr2

(array([[26, 23, 98],
        [13, 44, 49],
        [64, 16, 78]]),
 array([[75, 79, 18],
        [70, 99,  7],
        [96, 77, 89]]))

In [26]:
np.concatenate([arr1, arr2], axis = 0) #vstack

array([[26, 23, 98],
       [13, 44, 49],
       [64, 16, 78],
       [75, 79, 18],
       [70, 99,  7],
       [96, 77, 89]])

In [27]:
np.concatenate([arr1, arr2], axis = 1) # hstack

array([[26, 23, 98, 75, 79, 18],
       [13, 44, 49, 70, 99,  7],
       [64, 16, 78, 96, 77, 89]])

In [28]:
np.vstack((arr1, arr2))

array([[26, 23, 98],
       [13, 44, 49],
       [64, 16, 78],
       [75, 79, 18],
       [70, 99,  7],
       [96, 77, 89]])

In [29]:
np.hstack([arr1, arr2])

array([[26, 23, 98, 75, 79, 18],
       [13, 44, 49, 70, 99,  7],
       [64, 16, 78, 96, 77, 89]])