In [1]:
import numpy as np

1. Elementwise Operations
https://numpy.org/doc/2.5/reference/routines.math.html

In [2]:
a = np.array(
    [
        [4,6,8], 
        [1,2,4]
    ]
)
b = np.random.randint(1, 45, size = (2,3))
c = np.linspace((0,5), (60,100), num = 4, dtype=int)

In [3]:
a, b, c

(array([[4, 6, 8],
        [1, 2, 4]]),
 array([[35,  7,  6],
        [22, 28, 33]]),
 array([[  0,   5],
        [ 20,  36],
        [ 40,  68],
        [ 60, 100]]))

# Arithmetic Operations

In [4]:
# a + b
np.add(a,b)

array([[39, 13, 14],
       [23, 30, 37]])

In [5]:
# a -b 
np.subtract(a, b)

array([[-31,  -1,   2],
       [-21, -26, -29]])

In [6]:
# a ** 2
np.pow(a, 2)

array([[16, 36, 64],
       [ 1,  4, 16]])

In [7]:
# a % b
quo, rem = np.divmod(b,a)
rem

array([[3, 1, 6],
       [0, 0, 1]])

# Trignometric

In [8]:
np.sin(a)

array([[-0.7568025 , -0.2794155 ,  0.98935825],
       [ 0.84147098,  0.90929743, -0.7568025 ]])

In [9]:
cot = np.reciprocal(np.tan(b))
cot

array([[ 2.11052962e+00,  1.14751542e+00, -3.43635300e+00],
       [ 1.12973210e+02, -3.55328645e+00, -1.32779175e-02]])

# Rounding operations

In [10]:
np.around(cot, 2)

array([[ 2.1100e+00,  1.1500e+00, -3.4400e+00],
       [ 1.1297e+02, -3.5500e+00, -1.0000e-02]])

In [11]:
np.floor(cot)

array([[  2.,   1.,  -4.],
       [112.,  -4.,  -1.]])

In [12]:
np.ceil(cot)

array([[  3.,   2.,  -3.],
       [113.,  -3.,  -0.]])

 # 2. Matrix Operations

In [13]:
# Transpose

# b.T
bT = np.transpose(b)
bT

array([[35, 22],
       [ 7, 28],
       [ 6, 33]])

In [14]:
# Matrix Multiplication

# a @ bT
# np.dot(a, bT)
res = a.dot(bT)
res

array([[230, 520],
       [ 73, 210]])

In [15]:
# Trace [Diagnoal sum]
d_sum = np.trace(res)
print(d_sum)

440


In [16]:
# Rank
np.linalg.matrix_rank(a)

np.int64(2)

In [17]:
# Determinat
b = np.random.randint(1, 5, size = (3,3))

det_b = np.linalg.det(b)
det_b

np.float64(-6.0)

In [18]:
# Inverse
inv_b = np.linalg.inv(b)
inv_b

array([[ 1.16666667, -0.5       , -0.5       ],
       [ 1.33333333, -1.        ,  0.        ],
       [-2.16666667,  1.5       ,  0.5       ]])

Solve Equation : 4x + 2y = 8 , 5x + 3y = 9

In [19]:
A = np.array([[4,2] ,[5,3]])
B = np.array([8,9])

In [20]:
A_inv = np.linalg.inv(A)

In [21]:
X = np.dot(A_inv, B)

In [22]:
X

array([ 3., -2.])

In [23]:
# Array Broadcasting
A

array([[4, 2],
       [5, 3]])

In [24]:
B

array([8, 9])

In [25]:
A + B

array([[12, 11],
       [13, 12]])