# Installation
# uv pip install numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'2.5.2'

### Creating Numpy Array

In [7]:
#Rank 0 (scalar)

a = np.array(10)
a.ndim

0

In [8]:

#Rank 1 (vector)

a = np.array([1,2,3,4])
a.ndim

1

In [3]:
list1 = [1,2,3,4,5,6,7,8,9]

arry1 = np.array(list1)

In [4]:
arry1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arry1.shape

(9,)

In [6]:
arry1.ndim

1

In [9]:

#Rank 2 (matrix)

a = np.array([
    [1,2,3],
    [5,6,7]
])
a.ndim

2

In [10]:
list2 = [
    [1,2,3] , 
    [4,5,6] , 
    [7,8,9]
]
arry2 = np.array(list2)

In [11]:
arry2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arry2.shape

(3, 3)

In [13]:
arry2.ndim

2

In [14]:
list3 = [
    [
        [1,2,3] , 
        [4,5,6] , 
        [7,8,9]
    ],[
        [1,2,3] , 
        [4,5,6] , 
        [7,8,9]
    ]
]
arry3 = np.array(list3)

In [15]:
arry3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [16]:
arry3.shape

(2, 3, 3)

In [17]:
arry3.ndim

3

### NumPy Array Creation

NumPy arrays can be created in several ways. Here are some of the most common methods:

- `array()`: Creates NumPy arrays from Python lists
- `zeros()`: Creates NumPy arrays with all elements initialized to 0
- `ones()`: Creates NumPy arrays with all elements initialized to 1
- `full()`: Creates an array with all elements initialized to same user-specified value
- `arange()`: Creates NumPy arrays with a sequence of values (similar to python range() function)
- `linspace()`: Creates NumPy arrays with a sequence of evenly spaced values
- `diag()`: Creates NumPy array with the provided list of numbers as the diagonal elements and zeros elsewhere
- `eye()`: Creates NumPy array with ones on the diagonal and zeros elsewhere
- `identity()`: Creates an identity matrix
- `random.rand()`: Creates NumPy array of random numbers sampled from a uniform distribution

In [18]:

#create the 5 * 5 matrix and see the rank

a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
a.ndim

2

In [19]:
np.zeros(shape = (2, 3,6), dtype= "int")

array([[[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]])

In [20]:
np.ones(shape = (3,6,6), dtype="int")

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [21]:
np.full(shape = (3,4), fill_value=6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [22]:
full = np.full((2, 2, 3), fill_value=5)
full

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

In [23]:

# np.arange(start, stop, step):

# start = 2 (begin here)
# stop = 10 (stop before reaching this)
# step = 5 (increment by this amount each time)

arr = np.arange(2,10,5)
arr

array([2, 7])

In [24]:
np.arange(1,90,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86])

In [25]:
# np.linspace(start, stop, num):

# start = 0 (begin here)
# stop = 10 (end here - this IS included)
# num = 4 (how many evenly spaced points you want)

arr = np.linspace(0,10,4)
arr

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [26]:
np.linspace((0, 1, 2), (30,20, 60) , num = 5, axis=0)

array([[ 0.  ,  1.  ,  2.  ],
       [ 7.5 ,  5.75, 16.5 ],
       [15.  , 10.5 , 31.  ],
       [22.5 , 15.25, 45.5 ],
       [30.  , 20.  , 60.  ]])

In [27]:

# np.diag(v):

# Takes a 1D array: [1, 2, 3]
# Creates a 2D array with those values on the main diagonal
# Fills all other positions with 0

arr = np.diag([1,2,3])
arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [30]:

# np.identity(n):

# n = 3 (creates a 3×3 identity matrix)
# All 1's on the diagonal, 0's everywhere else

arr = np.identity(3) #can not be implement in (3,4) the rectangle matrix
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:

# np.eye(N):

# N = 3 (creates a 3×3 matrix)
# Puts 1's on the main diagonal
# Fills all other positions with 0

arr = np.eye(3) #can implement in (3,4) the rectangle matrix
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:

# np.random.rand(d0, d1, d2, ...):

# 2, 3 = creates a 2×3 array
# Fills it with random floats between 0 and 1
# Each time you run it, you get different values

arr = np.random.rand(2,3)
arr

array([[0.34297311, 0.48351544, 0.60574356],
       [0.23702627, 0.28217804, 0.35193452]])

In [32]:
np.random.randint(0, 50, size = (3, 2,4))

array([[[16, 21, 30, 25],
        [29, 23, 16, 27]],

       [[10, 38, 11, 36],
        [13, 19, 17, 38]],

       [[20, 48,  4, 23],
        [23, 20, 35,  7]]])